server: true
auto: true
exclude: docs README Gemfile Gemfile.lock CNAME
permalink:  :pretty

places:
  -
    city: Rio de Janeiro
    name: Antigamente Bar e Restaurante
    address: Rua do Ouvidor 43, Centro. Rio de Janeiro, RJ
    url: http://goo.gl/maps/pevBY
    embed_url: https://maps.google.com/maps?q=antigamente+ouvidor&amp;hl=en&amp;hq=antigamente+ouvidor&amp;radius=15000&amp;t=m&amp;ie=UTF8&amp;hnear=&amp;cid=14248734834522576877&amp;ll=-22.897406,-43.171592&amp;spn=0.018976,0.027466&amp;z=15&amp;iwloc=A&amp;output=embed
    twitter_url: https://twitter.com/horaextrario
  -
    city: João Pessoa
    name: Real Botequim - Mag Shopping
    address: Av. Governador Flávio Ribeiro Coutinho, 115, Manaíra. João Pessoa, PB
    url: http://goo.gl/maps/KrOif
    embed_url: https://maps.google.com/maps?q=real+botequim+joao+pessoa&amp;hl=en&amp;ie=UTF8&amp;sll=37.0625,-95.677068&amp;sspn=34.945679,64.248047&amp;t=m&amp;hq=real+botequim&amp;hnear=Jo%C3%A3o+Pessoa+-+Para%C3%ADba,+Brazil&amp;z=14&amp;iwloc=A&amp;cid=11812395456225338246&amp;ll=-7.097656,-34.833956&amp;output=embed
    twitter_url: https://twitter.com/horaextrajp