server: true
auto: true
exclude: docs README Gemfile Gemfile.lock CNAME
permalink:  :pretty

place:
  name: Antigamente Bar e Restaurante
  address: Rua do Ouvidor 43, Centro. Rio de Janeiro, RJ
  url: http://goo.gl/maps/pevBY
  embed_url: https://maps.google.com/maps?q=antigamente+ouvidor&amp;hl=en&amp;hq=antigamente+ouvidor&amp;radius=15000&amp;t=m&amp;ie=UTF8&amp;hnear=&amp;cid=14248734834522576877&amp;ll=-22.897406,-43.171592&amp;spn=0.018976,0.027466&amp;z=15&amp;iwloc=A&amp;output=embed