safe: true
lsi: false
pygments: true
exclude: ['docs', 'README', 'Gemfile', 'Gemfile.lock', 'CNAME']
permalink: :pretty

places:
  -
    city: Rio de Janeiro
    time: Toda segunda às 19:30h
    name: Bar Samba Caffé
    address: Rua do Ouvidor, 23, Rio de Janeiro, RJ
    geolocation: -22.902484,-43.175847
    url: http://goo.gl/maps/pBfQR
    twitter_url: https://twitter.com/horaextrario
  -
    city: Rio de Janeiro
    time: Toda segunda às 19:00
    name: Na Pressão
    address: Av. das Américas, 500 Bloco 06 - Lojas 120/121 Barra da Tijuca - Rio de Janeiro, RJ
    geolocation: -23.004551,-43.318203
    url: http://goo.gl/hJXd5z
    twitter_url: https://twitter.com/horaextrario
  -
    city: João Pessoa
    time: Encontros periódicos, acompanhe no twitter
    name: Real Botequim - Mag Shopping
    address: Av. Governador Flávio Ribeiro Coutinho, 115, Manaíra. João Pessoa, PB
    geolocation: -7.097656,-34.833956
    url: http://goo.gl/maps/KrOif
    twitter_url: https://twitter.com/horaextrajp
  -
    city: Salvador
    time: Toda segunda às 18:00h
    name: Café Feito a Grão - mezanino da Livraria Saraiva - Shopping Iguatemi
    address: Av. Tancredo Neves, 148, Caminho das Árvores. Salvador, BA
    geolocation: -12.98113,-38.464165
    url: http://goo.gl/maps/i6Rtk
    twitter_url: https://twitter.com/horaextrassa
  -
    city: Feira de Santana
    time: Toda terça às 18:30h
    name: Gauchão Lanches
    address: Avenida Getúlio Vargas, 2400, Santa Mônica. Feira de Santana, BA
    geolocation: -12.255637,-38.943765
    url: http://goo.gl/maps/MrVc4  
  -
    city: Maringá
    time: Todo sábado às 18:00h
    name: Pintxos
    address: Av. Pedro Taques, 91, Zona 03. Maringá, PR
    geolocation: -23.4201926,-51.9281692
    url: http://goo.gl/ChVyLQ
  -
    city: São José dos Campos
    time: Toda terça às 19:30h
    name: O Turco Gordo Lanchonete
    address: Rua Pedro de Toledo, 108, Vila Adyana. São José dos Campos, SP
    geolocation: -23.19887,-45.89378
    url: http://goo.gl/maps/8h88S
